/**
 * Hand-written types for the tables `20260826120000_legal_compliance.sql`
 * adds.
 *
 * **Why not `lib/supabase/database.types.ts`.** That file is generated by
 * `supabase gen types --linked`, which reads the *remote* schema — and this
 * migration has deliberately not been applied remotely. Pasting these tables
 * into the generated file would make `pnpm types:check` report a difference it
 * cannot explain, and the next `pnpm types:gen` would delete them again.
 *
 * So the compliance surface gets its own client (`lib/legal/db.ts`) typed by
 * this file. After the migration is applied and `pnpm types:gen` has run, this
 * file and the client can be deleted and the calls pointed at the ordinary
 * admin client — that is a mechanical follow-up, not a design.
 *
 * `events` appears here too, with only the columns this surface touches: the
 * retention run reads and writes two columns the generated type does not know
 * about yet.
 */

export type LegalDocumentKind =
  'host_terms' | 'early_performance' | 'guest_terms'

export type LegalRequestStatus =
  'received' | 'in_review' | 'more_info_requested' | 'accepted' | 'rejected'

export type ContentReportOutcome =
  | 'received'
  | 'more_info_requested'
  | 'no_action'
  | 'restricted'
  | 'removed'
  | 'event_restricted'

export type LegalAcceptanceRow = {
  id: string
  document: LegalDocumentKind
  legal_version: string
  user_id: string | null
  event_id: string | null
  participant_id: string | null
  event_slug: string | null
  subject_label: string | null
  ip_hash: string | null
  user_agent: string | null
  accepted_at: string
}

export type WithdrawalRequestRow = {
  id: string
  public_reference: string
  full_name: string
  order_reference: string
  email: string
  note: string | null
  legal_version: string
  status: LegalRequestStatus
  ip_hash: string | null
  user_agent: string | null
  submitted_at: string
  handled_at: string | null
  handling_note: string | null
}

export type ContentReportRow = {
  id: string
  public_reference: string
  reporter_name: string
  reporter_email: string
  event_reference: string
  content_reference: string
  reason: string
  legal_basis: string
  good_faith: boolean
  legal_version: string
  outcome: ContentReportOutcome
  ip_hash: string | null
  user_agent: string | null
  submitted_at: string
  handled_at: string | null
  handling_note: string | null
}

export type OutboundEmailRow = {
  id: string
  kind: string
  to_email: string
  subject: string
  body: string
  related_id: string | null
  attempts: number
  sent_at: string | null
  last_error: string | null
  provider_message_id: string | null
  created_at: string
}

/** Only the columns the retention run reads or writes. */
export type RetentionEventRow = {
  id: string
  slug: string
  event_name: string
  owner_id: string
  capture_end_at: string
  time_zone: string
  retention_warned_at: string | null
  legal_hold_at: string | null
  legal_hold_reason: string | null
}

type Table<Row, Insert = Partial<Row>, Update = Partial<Row>> = {
  Row: Row
  Insert: Insert
  Update: Update
  Relationships: []
}

export type LegalDatabase = {
  public: {
    Tables: {
      legal_acceptances: Table<
        LegalAcceptanceRow,
        Omit<LegalAcceptanceRow, 'id' | 'accepted_at'> &
          Partial<Pick<LegalAcceptanceRow, 'id' | 'accepted_at'>>
      >
      withdrawal_requests: Table<
        WithdrawalRequestRow,
        Omit<
          WithdrawalRequestRow,
          'id' | 'status' | 'submitted_at' | 'handled_at' | 'handling_note'
        > &
          Partial<
            Pick<
              WithdrawalRequestRow,
              'id' | 'status' | 'submitted_at' | 'handled_at' | 'handling_note'
            >
          >
      >
      content_reports: Table<
        ContentReportRow,
        Omit<
          ContentReportRow,
          'id' | 'outcome' | 'submitted_at' | 'handled_at' | 'handling_note'
        > &
          Partial<
            Pick<
              ContentReportRow,
              'id' | 'outcome' | 'submitted_at' | 'handled_at' | 'handling_note'
            >
          >
      >
      outbound_emails: Table<
        OutboundEmailRow,
        Omit<
          OutboundEmailRow,
          | 'id'
          | 'attempts'
          | 'sent_at'
          | 'last_error'
          | 'provider_message_id'
          | 'created_at'
        > &
          Partial<
            Pick<
              OutboundEmailRow,
              | 'id'
              | 'attempts'
              | 'sent_at'
              | 'last_error'
              | 'provider_message_id'
              | 'created_at'
            >
          >
      >
      events: Table<RetentionEventRow>
    }
    Views: Record<string, never>
    Functions: {
      events_awaiting_retention_warning: {
        Args: { p_limit: number }
        Returns: RetentionEventRow[]
      }
      events_due_for_deletion: {
        Args: { p_limit: number }
        Returns: RetentionEventRow[]
      }
    }
    Enums: {
      legal_document_kind: LegalDocumentKind
      legal_request_status: LegalRequestStatus
      content_report_outcome: ContentReportOutcome
    }
    CompositeTypes: Record<string, never>
  }
}
